import { escapeHTML as e, isFresh, releaseIssues } from './domain.mjs';
import { commerceDecision } from './commercial-offers.mjs';

const categories = { drawer: 'Drawers', underbed: 'Under the bed', wardrobe: 'Wardrobes', desk: 'Desks', shelf: 'Shelves' };
const dims = p => `${p.dimensionsMM.width} × ${p.dimensionsMM.depth} × ${p.dimensionsMM.height} mm`;
const chip = text => `<span class="chip">${e(text)}</span>`;
const euro = n => new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR' }).format(n);

export function viewData(p, origin, now) {
  return p.products.map(product => {
    const affiliate = commerceDecision(product, p, origin, now);
    return {
      ...product,
      merchantName: p.merchants.find(m => m.id === product.merchantId).name,
      affiliate,
      media: affiliate.active && affiliate.media ? affiliate.media : product.media,
      fresh: isFresh(product.source.checkedAt, p.site.sourceMaxAgeDays, now)
    };
  });
}

function productCard(p, { compare = true } = {}) {
  const destination = p.affiliate.active
    ? `<span class="ad-label">#Ad · affiliate link</span><a class="text-link" href="${e(p.affiliate.url)}" rel="sponsored nofollow noopener" target="_blank">View offer ↗</a>`
    : `<a class="text-link" href="${e(p.source.url)}" rel="noopener noreferrer" target="_blank">Manufacturer specification ↗</a>`;
  const commercial = p.affiliate.active && p.affiliate.price?.currency === 'EUR' && p.affiliate.pricePresentation?.approved === true
    ? `<p class="offer-price"><strong>${e(euro(p.affiliate.price.amount))}</strong><br><span class="small muted">${e(p.affiliate.pricePresentation.tax)} · ${e(p.affiliate.pricePresentation.delivery)} · provider feed checked ${e(p.affiliate.checkedAt || '')}. Retailer price at checkout controls.</span></p>`
    : '';
  return `<article class="product-card" data-product-id="${e(p.id)}" data-category="${e(p.category)}">
    <div class="card-top">${chip(categories[p.category])}${compare ? `<label class="compare-choice"><input type="checkbox" data-compare="${e(p.id)}"> Compare</label>` : ''}</div>
    <p class="small muted">${e(p.merchantName)} · ${e(p.sku)}</p><h3>${e(p.name)}</h3>
    ${commercial}<p class="dimensions">${e(dims(p))}</p><p>${e(p.note)}</p><p class="caution">${e(p.caution)}</p>
    ${p.minSpaceHeightMM ? `<p class="requirement">Minimum space height: ${p.minSpaceHeightMM} mm.</p>` : ''}
    ${p.maxWidthMM ? `<p class="small">Maximum expanded width: ${p.maxWidthMM} mm. Calculator uses compact size.</p>` : ''}
    <div class="source-note"><span class="dot ${p.fresh ? '' : 'stale'}"></span>${p.fresh ? 'Specification checked' : 'Specification needs recheck'} ${e(p.source.checkedAt)}<br>${p.affiliate.active ? `Affiliate offer source: ${e(p.affiliate.provider || p.affiliate.programId || 'approved programme')}.` : 'Stock and Irish delivery: not confirmed.'} No hands-on test.</div>${destination}
  </article>`;
}

function guideCard(g, i) {
  return `<article class="guide-card"><div class="card-top"><span class="number">${String(i + 1).padStart(2, '0')}</span>${chip(categories[g.category])}</div><h3><a href="/guides/${e(g.slug)}/">${e(g.title)}</a></h3><p>${e(g.summary)}</p><a class="text-link" href="/guides/${e(g.slug)}/">Read the guide →</a></article>`;
}

function layout(p, ctx, { path, title, description, body, page = '' }) {
  const preview = ctx.mode === 'preview';
  const current = route => path === route ? ' aria-current="page"' : '';
  const canonical = ctx.origin ? `<link rel="canonical" href="${e(ctx.origin + path)}">` : '';
  const operator = !preview && p.site.operator?.legalName && p.site.operator?.geographicAddress && p.site.operator?.contactEmail
    ? `<p class="small">Operator: ${e(p.site.operator.legalName)}${p.site.operator.publicName && p.site.operator.publicName !== p.site.operator.legalName ? ` · trading as ${e(p.site.operator.publicName)}` : ''}<br>${e(p.site.operator.geographicAddress)} · ${e(p.site.operator.contactEmail)}</p>`
    : '';
  return `<!doctype html><html lang="en-IE"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | ${e(p.site.name)}</title><meta name="description" content="${e(description)}"><meta name="robots" content="${preview ? 'noindex,nofollow' : 'index,follow'}"><meta name="theme-color" content="#203f37">${canonical}<link rel="stylesheet" href="/assets/styles.css"><script type="module" src="/assets/app.js"></script></head><body data-page="${e(page)}"><a class="skip" href="#main">Skip to content</a>${preview ? '<div class="preview-banner">PRIVATE-PREVIEW BUILD · Editorial drafts · No active affiliate partnerships · Not launched</div>' : ''}<header class="site-header wrap"><a class="brand" href="/" aria-label="DROPi Home, home"><span class="brand-mark" aria-hidden="true">d.</span><span>DROPi <b>Home</b></span></a><nav aria-label="Main navigation"><a href="/guides/"${current('/guides/')}>Guides</a><a href="/catalogue/"${current('/catalogue/')}>Research shortlist</a><a href="/fit/"${current('/fit/')}>Will it fit?</a><a href="/about/"${current('/about/')}>Our approach</a></nav></header><main id="main" class="wrap">${body}</main><footer class="site-footer"><div class="wrap footer-grid"><div><a class="brand" href="/">DROPi <b>Home</b></a><p>Practical organisation, without the guesswork.</p></div><div><p class="small">${e(p.site.monetization.enabled ? p.site.affiliateDisclosure : p.site.disclosure)}</p>${operator}<div class="footer-links"><a href="/disclosure/">Commercial disclosure</a><a href="/privacy/">Privacy</a>${preview ? '<a href="/ops/">Owner workspace</a>' : ''}</div></div></div></footer></body></html>`;
}

export function renderSite(p, ctx) {
  const products = viewData(p, ctx.origin, ctx.now);
  const pages = new Map();
  const add = (path, title, description, body, page = '') => pages.set(path, layout(p, ctx, { path, title, description, body, page }));

  add('/', 'Make room for what matters', 'Practical home organisation guides and a size-first product research shortlist.', `<section class="hero"><div class="hero-copy"><p class="eyebrow">SMALL SPACES. CONSIDERED CHOICES.</p><h1>A little more room.<br>A lot less <em>guesswork.</em></h1><p class="intro">Measure first. Compare what matters. Find a more useful home for the things you already own.</p><div class="actions"><a class="button" href="/fit/">Check your space ↗</a><a class="button secondary" href="/guides/">Explore the guides</a></div><p class="small muted">For homes in Ireland · No shop, checkout or invented reviews.</p></div><aside class="hero-panel"><div class="panel-heading"><span>THE FIT-FIRST METHOD</span><span>↗</span></div>${['Measure the usable space.','Read the actual specification.','Choose only what helps.'].map((x,i)=>`<div class="method-row"><span class="method-num">0${i+1}</span><div><h2>${x}</h2><p>${['Inside dimensions. Obstacles. Room to open.','The right variant, with a source you can check.','Sometimes, that means buying nothing.'][i]}</p></div></div>`).join('')}<div class="panel-foot"><span>Width × depth × height</span><span>Always in mm</span></div></aside></section><section class="trust-strip"><div><strong>${p.guides.length}</strong><span>${ctx.mode === 'preview' ? 'original guide drafts' : 'editorial guides'}</span></div><div><strong>${products.length}</strong><span>source-backed candidates</span></div><div><strong>No pretend tests.</strong><span>Specifications are not hands-on reviews.</span></div></section><section class="section"><div class="section-head"><div><p class="eyebrow">START WITH THE PROBLEM</p><h2>A useful guide before a new purchase.</h2></div><a class="text-link" href="/guides/">All guides →</a></div><div class="grid three">${p.guides.slice(0,3).map(guideCard).join('')}</div></section><section class="callout"><div><p class="eyebrow">A SMALL CHECK. A BETTER DECISION.</p><h2>That product name is not a fit guarantee.</h2><p>Compare your clear space with manufacturer-listed dimensions.</p></div><a class="button" href="/fit/">Try the fit checker →</a></section><section class="section"><div class="section-head"><div><p class="eyebrow">RESEARCH, NOT A SALES CATALOGUE</p><h2>Details you can inspect.</h2></div></div><div class="grid three">${products.slice(0,3).map(x=>productCard(x,{compare:false})).join('')}</div></section>`);

  add('/guides/', 'Practical guides', 'Original measurement and organisation guides for smaller spaces.', `<section class="page-head"><p class="eyebrow">THE GUIDES</p><h1>Make the space work<br>before you fill it.</h1><p class="intro">Practical measurement routines and buying checklists.</p></section><div class="grid three section">${p.guides.map(guideCard).join('')}</div>`);

  for (const g of p.guides) add(`/guides/${g.slug}/`, g.title, g.summary, `<div class="breadcrumb"><a href="/guides/">Guides</a> / ${e(categories[g.category])}</div><article class="reading"><header class="article-head">${chip(ctx.mode === 'preview' ? 'DRAFT · Not owner-approved' : 'Editorial guide')}<h1>${e(g.title)}</h1><p class="intro">${e(g.summary)}</p><p class="small muted">${e(g.authorship)}</p></header>${g.sections.map(s=>`<section><h2>${e(s.heading)}</h2>${s.paragraphs.map(t=>`<p>${e(t)}</p>`).join('')}</section>`).join('')}<aside class="checklist"><h2>Before you decide</h2><ul>${g.checklist.map(t=>`<li>${e(t)}</li>`).join('')}</ul></aside></article>${g.productIds.length ? `<section class="section"><div class="section-head"><div><p class="eyebrow">SOURCES & CANDIDATES</p><h2>Check the exact specification.</h2></div></div><div class="grid three">${products.filter(x=>g.productIds.includes(x.id)).map(x=>productCard(x,{compare:false})).join('')}</div></section>` : ''}`);

  const cats = [...new Set(products.map(x=>x.category))];
  add('/catalogue/', 'Research shortlist', 'Compare source-backed product dimensions and limitations.', `<section class="page-head"><p class="eyebrow">RESEARCH SHORTLIST</p><h1>Compare the facts,<br>not the sales pitch.</h1><p class="intro">Research candidates, not approved affiliate offers.</p></section><section class="filter-bar"><label>Search<input id="search" type="search" placeholder="Search candidates"></label><label>Category<select id="category"><option value="all">All spaces</option>${cats.map(c=>`<option value="${e(c)}">${e(categories[c])}</option>`).join('')}</select></label><p id="result-count" aria-live="polite">${products.length} candidates</p></section><p id="compare-message" class="small muted">0 selected. Choose up to three candidates to compare.</p><section id="comparison" class="comparison" hidden></section><p id="no-results" class="note" hidden>No candidates match those filters.</p><div class="grid three section">${products.map(productCard).join('')}</div>`, 'catalogue');

  add('/fit/', 'Will it fit?', 'Check published product dimensions against your measured space in millimetres.', `<section class="page-head"><p class="eyebrow">THE FIT CHECKER</p><h1>Measure once.<br>Question the assumptions.</h1><p class="intro">A geometric screen, not a guarantee.</p></section><div class="tool-grid section"><form id="fit-form" class="tool-card"><h2>Your usable space</h2><label>Candidate<select id="fit-product">${products.map(x=>`<option value="${e(x.id)}">${e(x.name)}</option>`).join('')}</select></label><div class="grid three"><label>Width (mm)<input id="width" required type="number" min="1" max="100000" step="0.1"></label><label>Depth (mm)<input id="depth" required type="number" min="1" max="100000" step="0.1"></label><label>Height (mm)<input id="height" required type="number" min="1" max="100000" step="0.1"></label></div><label>Total clearance per axis (mm)<input id="clearance" required type="number" min="0" max="1000" step="0.1" value="5"></label><label class="check-label"><input id="rotate" type="checkbox"> Allow a 90° turn on the base</label><button class="button" type="submit">Check the dimensions →</button></form><aside class="tool-card result-card"><p class="eyebrow">YOUR RESULT</p><div id="fit-result" role="status" aria-live="polite"><h2>A place for the facts.</h2><p>Choose a candidate and enter your measurements.</p></div><hr><p class="small">Geometric screening only. Check contents, movement, tolerances and manufacturer instructions.</p></aside></div>`, 'fit');

  add('/about/', 'Our approach', 'How DROPi Home researches product specifications and avoids unsupported claims.', `<section class="page-head"><p class="eyebrow">OUR APPROACH</p><h1>Useful before<br>commercial.</h1></section><article class="reading"><section><h2>Start with a specific problem</h2><p>We focus on practical organisation for smaller homes. We are not a shop or checkout service.</p></section><section><h2>Make evidence visible</h2><p>Each candidate has a manufacturer source, exact variant identifier and check date. These do not confirm stock, Irish delivery or affiliation.</p></section><section><h2>Specifications are not tests</h2><p>No hands-on product tests are claimed. Public release requires editorial review.</p></section></article>`);

  add('/disclosure/', 'Commercial disclosure', 'Affiliate status and the distinction between research and advertising links.', `<section class="page-head"><p class="eyebrow">TRANSPARENCY</p><h1>Know what a link means.</h1></section><article class="reading"><section><h2>${p.site.monetization.enabled ? 'Affiliate advertising' : 'No active affiliate monetisation'}</h2><p>${e(p.site.monetization.enabled ? p.site.affiliateDisclosure : p.site.disclosure)}</p><p>Every monetised link is marked <strong>#Ad</strong> before the link. Manufacturer links are research references unless explicitly labelled as affiliate advertisements.</p></section><section><h2>Where purchases happen</h2><p>The retailer controls prices, stock, delivery and purchase terms. DROPi Home has no cart, payment collection or fulfilment in the affiliate model.</p></section></article>`);

  add('/privacy/', 'Privacy', 'The data-minimising behaviour of the current DROPi Home build.', `<section class="page-head"><p class="eyebrow">PRIVACY</p><h1>Less data.<br>Fewer assumptions.</h1></section><article class="reading">${ctx.mode === 'preview' ? '<div class="note"><strong>DRAFT — Not a completed public privacy notice.</strong></div>' : `<p>Operator: ${e(p.site.operator.legalName)}${p.site.operator.publicName && p.site.operator.publicName !== p.site.operator.legalName ? ` trading as ${e(p.site.operator.publicName)}` : ''}. Address: ${e(p.site.operator.geographicAddress)}. Contact: ${e(p.site.operator.contactEmail)}.</p>`}<section><h2>What this application does</h2><p>No cookies, local storage, analytics scripts, conversion-tracking technologies, customer accounts, newsletter forms or checkout are used in the public affiliate build. Private administrator authentication is separate from public visitor behaviour.</p></section><section><h2>Requests and hosting</h2><p>Hosting infrastructure receives connection requests. Provider logging, retention, processor roles and lawful basis must be reviewed before public launch.</p></section><section><h2>Leaving this site</h2><p>External retailers have their own privacy practices.</p></section></article>`);

  if (ctx.mode === 'preview') {
    const blockers = releaseIssues(p, { SITE_ORIGIN: ctx.origin }, ctx.now);
    const inputs = [['visits','Monthly visits',10000,1e9,1],['outboundRate','Outbound click rate (%)',25,100,.1],['conversionRate','Purchase conversion (%)',4,100,.1],['basketEUR','Eligible basket (€)',80,1e6,.01],['commissionRate','Commission (%)',5,100,.1],['reversalRate','Reversed commission (%)',0,100,.1],['costsEUR','Monthly costs (€)',40,1e9,.01]];
    add('/ops/', 'Owner workspace', 'Preview-only release status and local evidence tools.', `<section class="page-head"><p class="eyebrow">OWNER WORKSPACE · PREVIEW ONLY</p><h1>Evidence before<br>expansion.</h1><p class="intro">No real traffic, sales or income has been verified.</p></section><section class="tool-card section"><h2>Public launch: ${blockers.length ? 'HOLD' : 'GATES PASSED'}</h2><p>${blockers.length} unresolved gates.</p><ul class="blocker-list">${blockers.map(t=>`<li>${e(t)}</li>`).join('')}</ul></section><section class="tool-grid section"><div class="tool-card"><p class="eyebrow">STATEMENTS, NOT INVENTED REVENUE</p><h2>Commission report viewer</h2><label>Ledger JSON<input id="ledger-file" type="file" accept="application/json,.json"></label><div id="ledger-result" role="status" aria-live="polite">No verified income data.</div></div><form id="scenario-form" class="tool-card"><p class="eyebrow">HYPOTHETICAL — NOT YOUR EARNINGS</p><h2>Test the assumptions</h2><div class="grid two">${inputs.map(([id,label,value,max,step])=>`<label>${label}<input id="${id}" type="number" required min="0" max="${max}" step="${step}" value="${value}"></label>`).join('')}</div><button class="button" type="submit">Calculate the scenario</button><div id="scenario-result" class="scenario-result" role="status" aria-live="polite">Illustrative inputs, not measured performance.</div></form></section>`, 'ops');
  }

  add('/404/', 'Page not found', 'The requested page does not exist.', '<section class="page-head"><p class="eyebrow">404</p><h1>A little lost?</h1><p>This page does not exist.</p><a class="button" href="/">Back home →</a></section>');
  return { pages, products };
}
